import type { CalculatorManifest } from "@/features/clinical-calculators/types";

export const apacheIiManifest: CalculatorManifest = {
  slug: "apache-ii",
  title: "APACHE II",
  shortTitle: "APACHE II",
  description: "Estime gravidade e risco de mortalidade em pacientes críticos nas primeiras 24 horas de UTI.",
  seoTitle: "APACHE II Calculator | Dosefy",
  seoDescription: "Calculate APACHE II score for ICU severity stratification.",
  heroEyebrow: "UTI",
  heroDescription:
    "Score clássico de gravidade que integra variáveis fisiológicas agudas, idade, Glasgow e saúde crônica.",
  heroHighlights: [
    "Usa o pior valor fisiológico das primeiras 24 horas.",
    "Mostra subtotais de APS, idade e saúde crônica.",
    "Estratificação rápida de risco hospitalar.",
  ],
  resultMetricLabel: "APACHE II",
  actionLabel: "Calcular APACHE II",
  note: "Use o pior valor de cada variável nas primeiras 24 horas da internação em UTI.",
  limitations: [
    "Não substitui julgamento clínico ou resposta dinâmica ao tratamento.",
    "Foi desenvolvido há décadas e convive hoje com escores mais recentes, como SOFA e APACHE IV.",
    "Depende de dados fisiológicos precisos e completos nas primeiras 24 horas.",
  ],
  references: [
    {
      label: "APACHE II: a severity of disease classification system",
      href: "https://pubmed.ncbi.nlm.nih.gov/3928249/",
    },
    {
      label: "Use of APACHE II in neurological intensive care patients",
      href: "https://ccforum.biomedcentral.com/articles/10.1186/cc2293",
    },
    {
      label: "Merck Manual Professional Edition",
      href: "https://www.merckmanuals.com/professional",
    },
  ],
  sections: [
    {
      id: "physiology",
      title: "Acute Physiology Score",
      description: "Variáveis fisiológicas agudas usadas para compor o APS.",
    },
    {
      id: "age",
      title: "Idade",
      description: "Pontos adicionais por faixa etária.",
    },
    {
      id: "chronic",
      title: "Saúde crônica",
      description: "Marque apenas se houver insuficiência orgânica grave prévia ou imunossupressão.",
    },
  ],
  fields: [
    {
      name: "temperature",
      label: "Temperatura retal",
      type: "number",
      sectionId: "physiology",
      placeholder: "Ex.: 37.0",
      inputMode: "decimal",
      step: 0.1,
      suffix: "°C",
    },
    {
      name: "meanArterialPressure",
      label: "PAM / MAP",
      type: "number",
      sectionId: "physiology",
      placeholder: "Ex.: 85",
      inputMode: "numeric",
      suffix: "mmHg",
    },
    {
      name: "heartRate",
      label: "Frequência cardíaca",
      type: "number",
      sectionId: "physiology",
      placeholder: "Ex.: 88",
      inputMode: "numeric",
      suffix: "bpm",
    },
    {
      name: "respiratoryRate",
      label: "Frequência respiratória",
      type: "number",
      sectionId: "physiology",
      placeholder: "Ex.: 18",
      inputMode: "numeric",
      suffix: "irpm",
    },
    {
      name: "oxygenationMode",
      label: "Método de oxigenação",
      type: "select",
      sectionId: "physiology",
      options: [
        { label: "FiO2 ≥ 0,5: usar A-aDO2", value: "aa_gradient" },
        { label: "FiO2 < 0,5: usar PaO2", value: "pao2" },
      ],
    },
    {
      name: "oxygenationValue",
      label: "Valor da oxigenação",
      type: "number",
      sectionId: "physiology",
      placeholder: "Ex.: 320",
      inputMode: "decimal",
      description: "Informe A-aDO2 se FiO2 >= 0,5; caso contrário, informe PaO2.",
      suffix: "mmHg",
    },
    {
      name: "arterialPh",
      label: "pH arterial",
      type: "number",
      sectionId: "physiology",
      placeholder: "Ex.: 7.40",
      inputMode: "decimal",
      step: 0.01,
    },
    {
      name: "sodium",
      label: "Sódio sérico",
      type: "number",
      sectionId: "physiology",
      placeholder: "Ex.: 140",
      inputMode: "decimal",
      suffix: "mmol/L",
    },
    {
      name: "potassium",
      label: "Potássio sérico",
      type: "number",
      sectionId: "physiology",
      placeholder: "Ex.: 4.0",
      inputMode: "decimal",
      step: 0.1,
      suffix: "mmol/L",
    },
    {
      name: "creatinine",
      label: "Creatinina sérica",
      type: "number",
      sectionId: "physiology",
      placeholder: "Ex.: 1.0",
      inputMode: "decimal",
      step: 0.1,
      suffix: "mg/dL",
    },
    {
      name: "acuteRenalFailure",
      label: "Insuficiência renal aguda presente",
      type: "checkbox",
      sectionId: "physiology",
      description: "Dobra a pontuação da creatinina, conforme regra clássica do APACHE II.",
      colSpan: 2,
    },
    {
      name: "hematocrit",
      label: "Hematócrito",
      type: "number",
      sectionId: "physiology",
      placeholder: "Ex.: 40",
      inputMode: "decimal",
      suffix: "%",
    },
    {
      name: "whiteBloodCells",
      label: "Leucócitos",
      type: "number",
      sectionId: "physiology",
      placeholder: "Ex.: 9",
      inputMode: "decimal",
      suffix: "x10³/mm³",
    },
    {
      name: "glasgowComaScale",
      label: "Glasgow Coma Scale",
      type: "number",
      sectionId: "physiology",
      placeholder: "Ex.: 15",
      inputMode: "numeric",
      min: 3,
      max: 15,
    },
    {
      name: "age",
      label: "Idade",
      type: "number",
      sectionId: "age",
      placeholder: "Ex.: 64",
      inputMode: "numeric",
      suffix: "anos",
    },
    {
      name: "chronicHealth",
      label: "Há insuficiência orgânica grave prévia ou imunossupressão",
      type: "checkbox",
      sectionId: "chronic",
      colSpan: 2,
    },
    {
      name: "chronicHealthContext",
      label: "Contexto clínico",
      type: "select",
      sectionId: "chronic",
      visibility: [{ field: "chronicHealth", equals: true }],
      options: [
        { label: "Pós-operatório eletivo", value: "elective_postop" },
        { label: "Pós-operatório de urgência ou não operatório", value: "emergency_postop_or_medical" },
      ],
    },
  ],
  initialValues: {
    temperature: "",
    meanArterialPressure: "",
    heartRate: "",
    respiratoryRate: "",
    oxygenationMode: "pao2",
    oxygenationValue: "",
    arterialPh: "",
    sodium: "",
    potassium: "",
    creatinine: "",
    acuteRenalFailure: false,
    hematocrit: "",
    whiteBloodCells: "",
    glasgowComaScale: "",
    age: "",
    chronicHealth: false,
    chronicHealthContext: "none",
  },
};

export const calculatorManifest = apacheIiManifest;
